# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calib_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calib_Window(object):
    def setupUi(self, Calib_Window):
        Calib_Window.setObjectName("Calib_Window")
        Calib_Window.resize(621, 654)
        self.Button_save_calib = QtWidgets.QPushButton(Calib_Window)
        self.Button_save_calib.setGeometry(QtCore.QRect(50, 470, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_save_calib.setFont(font)
        self.Button_save_calib.setObjectName("Button_save_calib")
        self.Button_close_calib = QtWidgets.QPushButton(Calib_Window)
        self.Button_close_calib.setGeometry(QtCore.QRect(50, 550, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_close_calib.setFont(font)
        self.Button_close_calib.setObjectName("Button_close_calib")
        self.Button_calib = QtWidgets.QPushButton(Calib_Window)
        self.Button_calib.setGeometry(QtCore.QRect(180, 470, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_calib.setFont(font)
        self.Button_calib.setObjectName("Button_calib")
        self.text_calib = QtWidgets.QTextEdit(Calib_Window)
        self.text_calib.setGeometry(QtCore.QRect(320, 450, 271, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.text_calib.setFont(font)
        self.text_calib.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(163, 163, 163, 255), stop:1 rgba(255, 255, 255, 255));")
        self.text_calib.setObjectName("text_calib")
        self.label = QtWidgets.QLabel(Calib_Window)
        self.label.setGeometry(QtCore.QRect(30, 450, 271, 181))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(163, 163, 163, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.image_calib = QtWidgets.QLabel(Calib_Window)
        self.image_calib.setGeometry(QtCore.QRect(30, 70, 561, 361))
        self.image_calib.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.image_calib.setFrameShape(QtWidgets.QFrame.Box)
        self.image_calib.setText("")
        self.image_calib.setScaledContents(True)
        self.image_calib.setObjectName("image_calib")
        self.Button_cam_calib = QtWidgets.QPushButton(Calib_Window)
        self.Button_cam_calib.setGeometry(QtCore.QRect(180, 550, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_cam_calib.setFont(font)
        self.Button_cam_calib.setObjectName("Button_cam_calib")
        self.label_3 = QtWidgets.QLabel(Calib_Window)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 561, 41))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.534, x2:1, y2:0.551, stop:0 rgba(0, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_3.setObjectName("label_3")
        self.Button_camid = QtWidgets.QPushButton(Calib_Window)
        self.Button_camid.setGeometry(QtCore.QRect(260, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_camid.setFont(font)
        self.Button_camid.setText("")
        self.Button_camid.setFlat(True)
        self.Button_camid.setObjectName("Button_camid")
        self.label_3.raise_()
        self.label.raise_()
        self.Button_save_calib.raise_()
        self.Button_close_calib.raise_()
        self.Button_calib.raise_()
        self.text_calib.raise_()
        self.image_calib.raise_()
        self.Button_cam_calib.raise_()
        self.Button_camid.raise_()

        self.retranslateUi(Calib_Window)
        QtCore.QMetaObject.connectSlotsByName(Calib_Window)

    def retranslateUi(self, Calib_Window):
        _translate = QtCore.QCoreApplication.translate
        Calib_Window.setWindowTitle(_translate("Calib_Window", "Calib"))
        self.Button_save_calib.setText(_translate("Calib_Window", "Save"))
        self.Button_close_calib.setText(_translate("Calib_Window", "Close"))
        self.Button_calib.setText(_translate("Calib_Window", "Calib"))
        self.Button_cam_calib.setToolTip(_translate("Calib_Window", "Connect Camera"))
        self.Button_cam_calib.setText(_translate("Calib_Window", "Cam"))
        self.label_3.setText(_translate("Calib_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">CALIB</span></p></body></html>"))
        self.Button_camid.setToolTip(_translate("Calib_Window", "Select cam id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calib_Window = QtWidgets.QWidget()
    ui = Ui_Calib_Window()
    ui.setupUi(Calib_Window)
    Calib_Window.show()
    sys.exit(app.exec_())
