# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exit_window(object):
    def setupUi(self, Exit_window):
        Exit_window.setObjectName("Exit_window")
        Exit_window.resize(480, 161)
        Exit_window.setMinimumSize(QtCore.QSize(480, 0))
        Exit_window.setMaximumSize(QtCore.QSize(480, 171))
        Exit_window.setWindowTitle("Exit")
        Exit_window.setStyleSheet("")
        self.label = QtWidgets.QLabel(Exit_window)
        self.label.setGeometry(QtCore.QRect(20, 13, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Button_yes = QtWidgets.QPushButton(Exit_window)
        self.Button_yes.setGeometry(QtCore.QRect(260, 90, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_yes.setFont(font)
        self.Button_yes.setStyleSheet("")
        self.Button_yes.setObjectName("Button_yes")
        self.Button_no = QtWidgets.QPushButton(Exit_window)
        self.Button_no.setGeometry(QtCore.QRect(370, 90, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_no.setFont(font)
        self.Button_no.setStyleSheet("")
        self.Button_no.setObjectName("Button_no")
        self.label_2 = QtWidgets.QLabel(Exit_window)
        self.label_2.setGeometry(QtCore.QRect(5, 69, 470, 87))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.522, x2:1, y2:0.545091, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(173, 173, 173, 255));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Exit_window)
        self.label_3.setGeometry(QtCore.QRect(5, 5, 470, 68))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.517, x2:1, y2:0.551, stop:0 rgba(255, 170, 127, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.Button_yes.raise_()
        self.Button_no.raise_()

        self.retranslateUi(Exit_window)
        QtCore.QMetaObject.connectSlotsByName(Exit_window)

    def retranslateUi(self, Exit_window):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Exit_window", "Are you sure you want to exist ?"))
        self.Button_yes.setText(_translate("Exit_window", "Yes"))
        self.Button_no.setText(_translate("Exit_window", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Exit_window = QtWidgets.QWidget()
    ui = Ui_Exit_window()
    ui.setupUi(Exit_window)
    Exit_window.show()
    sys.exit(app.exec_())
