# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 995)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.phat_hien_loi = QtWidgets.QScrollArea(self.centralwidget)
        self.phat_hien_loi.setEnabled(True)
        self.phat_hien_loi.setGeometry(QtCore.QRect(1470, 70, 391, 901))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.phat_hien_loi.sizePolicy().hasHeightForWidth())
        self.phat_hien_loi.setSizePolicy(sizePolicy)
        self.phat_hien_loi.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.phat_hien_loi.setFont(font)
        self.phat_hien_loi.setMouseTracking(True)
        self.phat_hien_loi.setTabletTracking(True)
        self.phat_hien_loi.setAcceptDrops(True)
        self.phat_hien_loi.setAutoFillBackground(True)
        self.phat_hien_loi.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(175, 175, 175, 255), stop:1 rgba(255, 255, 255, 255));")
        self.phat_hien_loi.setFrameShape(QtWidgets.QFrame.Box)
        self.phat_hien_loi.setLineWidth(2)
        self.phat_hien_loi.setWidgetResizable(True)
        self.phat_hien_loi.setObjectName("phat_hien_loi")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 383, 893))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.phat_hien_loi.setWidget(self.scrollAreaWidgetContents)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(750, 70, 683, 441))
        self.image.setSizeIncrement(QtCore.QSize(0, 0))
        self.image.setMouseTracking(False)
        self.image.setTabletTracking(False)
        self.image.setAutoFillBackground(False)
        self.image.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setLineWidth(1)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.cam = QtWidgets.QLabel(self.centralwidget)
        self.cam.setGeometry(QtCore.QRect(40, 70, 680, 441))
        self.cam.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.cam.setFrameShape(QtWidgets.QFrame.Box)
        self.cam.setText("")
        self.cam.setScaledContents(True)
        self.cam.setObjectName("cam")
        self.message = QtWidgets.QTextEdit(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(750, 530, 321, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.message.setFont(font)
        self.message.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(163, 163, 163, 255), stop:1 rgba(255, 255, 255, 255));")
        self.message.setFrameShape(QtWidgets.QFrame.Box)
        self.message.setLineWidth(2)
        self.message.setObjectName("message")
        self.image1 = QtWidgets.QLabel(self.centralwidget)
        self.image1.setGeometry(QtCore.QRect(40, 530, 680, 441))
        self.image1.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.image1.setFrameShape(QtWidgets.QFrame.Box)
        self.image1.setText("")
        self.image1.setScaledContents(True)
        self.image1.setObjectName("image1")
        self.ket_qua = QtWidgets.QLabel(self.centralwidget)
        self.ket_qua.setGeometry(QtCore.QRect(1100, 530, 331, 211))
        font = QtGui.QFont()
        font.setPointSize(54)
        font.setBold(True)
        font.setWeight(75)
        self.ket_qua.setFont(font)
        self.ket_qua.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 170, 255, 255), stop:1 rgba(255, 255, 164, 255));")
        self.ket_qua.setFrameShape(QtWidgets.QFrame.Box)
        self.ket_qua.setObjectName("ket_qua")
        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(1110, 780, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_start.setFont(font)
        self.Button_start.setStyleSheet("QPushButton#Button_start{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 198, 25, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton#Button_start:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton#Button_start:pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 127, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.Button_start.setObjectName("Button_start")
        self.Button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop.setGeometry(QtCore.QRect(1220, 780, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_stop.setFont(font)
        self.Button_stop.setStyleSheet("\n"
"\n"
"QPushButton#Button_stop{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 0, 255, 255), stop:1 rgba(255, 170, 255, 255));\n"
"}\n"
"\n"
"QPushButton#Button_stop:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton#Button_stop:pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 127, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.Button_stop.setObjectName("Button_stop")
        self.Button_calib = QtWidgets.QPushButton(self.centralwidget)
        self.Button_calib.setGeometry(QtCore.QRect(1110, 860, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_calib.setFont(font)
        self.Button_calib.setStyleSheet("")
        self.Button_calib.setObjectName("Button_calib")
        self.Button_train = QtWidgets.QPushButton(self.centralwidget)
        self.Button_train.setGeometry(QtCore.QRect(1220, 860, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_train.setFont(font)
        self.Button_train.setStyleSheet("")
        self.Button_train.setObjectName("Button_train")
        self.Button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.Button_reset.setGeometry(QtCore.QRect(1330, 860, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_reset.setFont(font)
        self.Button_reset.setStyleSheet("")
        self.Button_reset.setObjectName("Button_reset")
        self.Button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_exit.setGeometry(QtCore.QRect(1330, 780, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Button_exit.setFont(font)
        self.Button_exit.setStyleSheet("\n"
"\n"
"QPushButton#Button_exit{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(232, 0, 0, 255), stop:1 rgba(255, 201, 255, 255));\n"
"}\n"
"\n"
"QPushButton#Button_exit:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton#Button_exit:pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 127, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.Button_exit.setObjectName("Button_exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1100, 770, 331, 161))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(163, 163, 163, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.ket_qua_2 = QtWidgets.QLabel(self.centralwidget)
        self.ket_qua_2.setGeometry(QtCore.QRect(40, 0, 1821, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.ket_qua_2.setFont(font)
        self.ket_qua_2.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.523, x2:1, y2:0.528, stop:0 rgba(255, 170, 255, 255), stop:1 rgba(255, 170, 127, 255));")
        self.ket_qua_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ket_qua_2.setObjectName("ket_qua_2")
        self.label.raise_()
        self.phat_hien_loi.raise_()
        self.image.raise_()
        self.cam.raise_()
        self.message.raise_()
        self.image1.raise_()
        self.ket_qua.raise_()
        self.Button_start.raise_()
        self.Button_stop.raise_()
        self.Button_calib.raise_()
        self.Button_train.raise_()
        self.Button_reset.raise_()
        self.Button_exit.raise_()
        self.ket_qua_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "A DEFECT DETECTION SYSTEM FOR PCB MANUFACTURING"))
        self.ket_qua.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">RESULT </p></body></html>"))
        self.Button_start.setText(_translate("MainWindow", "START"))
        self.Button_stop.setText(_translate("MainWindow", "STOP"))
        self.Button_calib.setText(_translate("MainWindow", "CALIB"))
        self.Button_train.setText(_translate("MainWindow", "DATA"))
        self.Button_reset.setText(_translate("MainWindow", "RESET"))
        self.Button_exit.setText(_translate("MainWindow", "EXIT"))
        self.ket_qua_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">A DEFECT DETECTION SYSTEM FOR PCB MANUFACTURING</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
