# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Restart_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Restart_window(object):
    def setupUi(self, Restart_window):
        Restart_window.setObjectName("Restart_window")
        Restart_window.resize(487, 196)
        self.Button_yes = QtWidgets.QPushButton(Restart_window)
        self.Button_yes.setGeometry(QtCore.QRect(270, 123, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_yes.setFont(font)
        self.Button_yes.setStyleSheet("")
        self.Button_yes.setObjectName("Button_yes")
        self.label_3 = QtWidgets.QLabel(Restart_window)
        self.label_3.setGeometry(QtCore.QRect(5, 5, 477, 101))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.517, x2:1, y2:0.545, stop:0 rgba(255, 170, 127, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Button_no = QtWidgets.QPushButton(Restart_window)
        self.Button_no.setGeometry(QtCore.QRect(380, 123, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Button_no.setFont(font)
        self.Button_no.setStyleSheet("")
        self.Button_no.setObjectName("Button_no")
        self.label = QtWidgets.QLabel(Restart_window)
        self.label.setGeometry(QtCore.QRect(20, 5, 461, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Restart_window)
        self.label_2.setGeometry(QtCore.QRect(5, 100, 477, 91))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.522, x2:1, y2:0.545091, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(173, 173, 173, 255));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.Button_yes.raise_()
        self.label_3.raise_()
        self.Button_no.raise_()
        self.label.raise_()

        self.retranslateUi(Restart_window)
        QtCore.QMetaObject.connectSlotsByName(Restart_window)

    def retranslateUi(self, Restart_window):
        _translate = QtCore.QCoreApplication.translate
        Restart_window.setWindowTitle(_translate("Restart_window", "Restart"))
        self.Button_yes.setText(_translate("Restart_window", "Yes"))
        self.Button_no.setText(_translate("Restart_window", "No"))
        self.label.setText(_translate("Restart_window", "<html><head/><body><p>Conveyor is not connected !</p><p>Do you want to exit the program?</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Restart_window = QtWidgets.QWidget()
    ui = Ui_Restart_window()
    ui.setupUi(Restart_window)
    Restart_window.show()
    sys.exit(app.exec_())
