# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wait_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wait(object):
    def setupUi(self, wait):
        wait.setObjectName("wait")
        wait.resize(400, 93)
        self.label = QtWidgets.QLabel(wait)
        self.label.setGeometry(QtCore.QRect(100, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(wait)
        QtCore.QMetaObject.connectSlotsByName(wait)

    def retranslateUi(self, wait):
        _translate = QtCore.QCoreApplication.translate
        wait.setWindowTitle(_translate("wait", "Loading"))
        self.label.setText(_translate("wait", "Please Wait ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wait = QtWidgets.QWidget()
    ui = Ui_wait()
    ui.setupUi(wait)
    wait.show()
    sys.exit(app.exec_())
